// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package hasher

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson76af75b5DecodeGithubComIlyushaZMegafonTestInternalHasher(in *jlexer.Lexer, out *Body) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "phrase":
			out.Phrase = string(in.String())
		case "hash":
			out.Hash = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson76af75b5EncodeGithubComIlyushaZMegafonTestInternalHasher(out *jwriter.Writer, in Body) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"phrase\":"
		out.RawString(prefix[1:])
		out.String(string(in.Phrase))
	}
	{
		const prefix string = ",\"hash\":"
		out.RawString(prefix)
		out.Int64(int64(in.Hash))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Body) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson76af75b5EncodeGithubComIlyushaZMegafonTestInternalHasher(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Body) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson76af75b5EncodeGithubComIlyushaZMegafonTestInternalHasher(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Body) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson76af75b5DecodeGithubComIlyushaZMegafonTestInternalHasher(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Body) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson76af75b5DecodeGithubComIlyushaZMegafonTestInternalHasher(l, v)
}
func easyjson76af75b5DecodeGithubComIlyushaZMegafonTestInternalHasher1(in *jlexer.Lexer, out *ArrBody) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(ArrBody, 0, 2)
			} else {
				*out = ArrBody{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 Body
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson76af75b5EncodeGithubComIlyushaZMegafonTestInternalHasher1(out *jwriter.Writer, in ArrBody) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v ArrBody) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson76af75b5EncodeGithubComIlyushaZMegafonTestInternalHasher1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ArrBody) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson76af75b5EncodeGithubComIlyushaZMegafonTestInternalHasher1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ArrBody) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson76af75b5DecodeGithubComIlyushaZMegafonTestInternalHasher1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ArrBody) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson76af75b5DecodeGithubComIlyushaZMegafonTestInternalHasher1(l, v)
}
